apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-v1
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backend.name }}
    version: v1
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        version: v1
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: MONGO_URI
          value: {{ .Values.backend.mongoUri | quote }}
        resources:
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.name }}-v2
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.backend.name }}
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
      version: v2
  template:
    metadata:
      labels:
        app: {{ .Values.backend.name }}
        version: v2
    spec:
      containers:
      - name: {{ .Values.backend.name }}
        image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}
        ports:
        - containerPort: {{ .Values.backend.port }}
        env:
        - name: MONGO_URI
          value: {{ .Values.backend.mongoUri | quote }}
        resources:
          limits:
            cpu: {{ .Values.backend.resources.limits.cpu }}
            memory: {{ .Values.backend.resources.limits.memory }}
          requests:
            cpu: {{ .Values.backend.resources.requests.cpu }}
            memory: {{ .Values.backend.resources.requests.memory }}
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.backend.port }}
          initialDelaySeconds: 15
          periodSeconds: 10