apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.frontend.servicePort }}
    targetPort: {{ .Values.frontend.port }}
  selector:
    app: {{ .Values.frontend.name }}
  type: ClusterIP