apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
type: Opaque
data:
  MONGO_URI: bW9uZ29kYjovL2YyMTk0NjI6T3hqZTNkY09FSk1pelBSekBjbHVzdGVyMC4wZGk1cS5tb25nb2RiLm5ldC9Ub0RvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==