apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mongodb
  description: MongoDB Database for Todo Application
spec:
  type: database
  owner: user:default/admin
  system: todo-application