apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Release.Namespace }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  BACKEND_PORT: {{ .Values.config.backendPort | quote }}
  FRONTEND_PORT: {{ .Values.config.frontendPort | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}