apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AbubakarMahmood1/todo-app.git
    targetRevision: main
    path: charts/todo-app
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true