apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 1h
  chart:
    spec:
      chart: gatekeeper
      version: "3.9.x"
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: gatekeeper-system
  values:
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 1h
  url: https://open-policy-agent.github.io/gatekeeper/charts