name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        
    - name: Install dependencies
      run: |
        cd backend || true
        npm ci || npm install || echo "Backend dependencies installation skipped"
        cd ../frontend || true
        npm ci || npm install || echo "Frontend dependencies installation skipped"
      continue-on-error: true
      
    - name: Build check
      run: echo "Build verification would happen here in a production environment"