name: frontend-pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin
      - name: Build Docker image
        run: docker build -t frontend:0.0.1 ./frontend
      - name: Tag Docker image
        run: docker tag frontend:0.0.1 ${{ secrets.DOCKERHUB_USER }}/frontend:0.0.1
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USER }}/frontend:0.0.1
